# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc32f7f803c8878bacf73b9d0ee2e78922c614a2af43d075e1e3c5c62cbde6d9c705b2cef8b43a31154c2e404274a5a7d00ae8d64d4a7455754f7860d580dc88

test:
  secret_key_base: 352caa3f3325e14188a80e1793a964bdf3b346391aa902d60f82f62ff3bac88f18c30be9d97b73209ddf80150e22df8885974014ade7f7885f9c009fd704b83d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
